apiVersion: v2
name: store-trigger
description: A Helm chart for store-trigger service
type: application
version: 2.0.3
appVersion: 2.0.3
dependencies:
  - name: mc-labels-and-annotations
    version: 0.7.0
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
    alias: mcLabelsAndAnnotations
